language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

install:
 - pip install nose setuptools --upgrade
 - python setup.py develop
script: nosetests -v
